import styled from "styled-components";

export const Explorer = styled.div`display:grid;grid-template-columns:minmax(16rem,.65fr) minmax(0,1.6fr);gap:${({ theme }) => theme.spacing.lg};align-items:start;@media(max-width:62rem){grid-template-columns:1fr;}`;
export const Library = styled.div`display:grid;gap:${({ theme }) => theme.spacing.md};padding:${({ theme }) => theme.spacing.md};`;
export const VaultList = styled.div`display:grid;gap:.35rem;`;
export const VaultButton = styled.button<{ $active: boolean }>`display:grid;grid-template-columns:auto minmax(0,1fr) auto;align-items:center;gap:${({ theme }) => theme.spacing.sm};width:100%;border:1px solid ${({ theme, $active }) => ($active ? theme.colors.lineStrong : "transparent")};border-radius:${({ theme }) => theme.radius.control};padding:.75rem;background:${({ theme, $active }) => ($active ? theme.colors.surfaceAccent : "transparent")};color:${({ theme, $active }) => ($active ? theme.colors.primary : theme.colors.textMuted)};font:inherit;text-align:left;cursor:pointer;&:hover{background:${({ theme }) => theme.colors.surfaceAccent};}`;
export const VaultCopy = styled.span`min-width:0;strong,span{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;}strong{color:${({ theme }) => theme.colors.text};font-size:.72rem;}span{margin-top:.18rem;color:${({ theme }) => theme.colors.textSubtle};font-size:.58rem;text-transform:capitalize;}`;
export const Summary = styled.div`display:flex;align-items:center;justify-content:space-between;gap:${({ theme }) => theme.spacing.md};padding:${({ theme }) => theme.spacing.md};border-bottom:1px solid ${({ theme }) => theme.colors.line};@media(max-width:40rem){align-items:stretch;flex-direction:column;}`;
export const MetaGrid = styled.div`display:flex;flex-wrap:wrap;gap:${({ theme }) => theme.spacing.sm};`;
export const MetaItem = styled.div`display:grid;gap:.15rem;min-width:6.5rem;padding:.55rem .7rem;border-radius:${({ theme }) => theme.radius.control};background:${({ theme }) => theme.colors.background};span{color:${({ theme }) => theme.colors.textSubtle};font-size:.56rem;text-transform:uppercase;}strong{font-size:.7rem;text-transform:capitalize;}`;
export const SourceAction = styled.div`flex:0 0 auto;`;
export const FileInput = styled.input`position:absolute;width:1px;height:1px;overflow:hidden;clip:rect(0,0,0,0);white-space:nowrap;`;
export const SourceList = styled.div`display:grid;`;
export const SourceRow = styled.div`display:grid;grid-template-columns:auto minmax(0,1fr) auto;align-items:center;gap:${({ theme }) => theme.spacing.sm};padding:${({ theme }) => theme.spacing.md};border-bottom:1px solid ${({ theme }) => theme.colors.line};color:${({ theme }) => theme.colors.primary};>div{min-width:0;}strong,span{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;}strong{color:${({ theme }) => theme.colors.text};font-size:.72rem;}span{margin-top:.2rem;color:${({ theme }) => theme.colors.textSubtle};font-size:.6rem;}`;
export const SourceStatus = styled.span<{ $local: boolean }>`display:flex!important;align-items:center;gap:.3rem!important;color:${({ theme, $local }) => ($local ? theme.colors.accentSoft : theme.colors.statusOnline)}!important;font-size:.58rem!important;font-weight:700;text-transform:capitalize;`;
