import styled from "styled-components";

export const ProjectsGrid = styled.div`display:grid;grid-template-columns:minmax(0,1.3fr) minmax(18rem,.7fr);gap:${({ theme }) => theme.spacing.lg};align-items:start;@media(max-width:62rem){grid-template-columns:1fr;}`;
export const ProjectList = styled.div`display:grid;gap:${({ theme }) => theme.spacing.md};padding:${({ theme }) => theme.spacing.md};`;
export const ProjectCard = styled.button`display:grid;grid-template-columns:auto minmax(0,1fr);align-items:start;gap:${({ theme }) => theme.spacing.md};width:100%;border:1px solid ${({ theme }) => theme.colors.lineStrong};border-radius:${({ theme }) => theme.radius.control};padding:${({ theme }) => theme.spacing.md};background:${({ theme }) => theme.colors.surfaceAccent};color:${({ theme }) => theme.colors.primary};font:inherit;text-align:left;cursor:pointer;`;
export const ProjectTitle = styled.div`min-width:0;strong,span{display:block;}strong{color:${({ theme }) => theme.colors.text};font-size:.82rem;}span{overflow:hidden;margin-top:.2rem;color:${({ theme }) => theme.colors.textMuted};font-size:.64rem;text-overflow:ellipsis;white-space:nowrap;}`;
export const ProjectMeta = styled.div`display:flex;align-items:center;gap:${({ theme }) => theme.spacing.sm};margin-top:.7rem;small{color:${({ theme }) => theme.colors.textSubtle};font-size:.6rem;}`;
export const Authorize = styled.div`display:grid;gap:${({ theme }) => theme.spacing.md};padding:${({ theme }) => theme.spacing.md};`;
export const SafetyNote = styled.div`display:flex;align-items:flex-start;gap:${({ theme }) => theme.spacing.sm};padding:${({ theme }) => theme.spacing.sm};border-radius:${({ theme }) => theme.radius.control};background:${({ theme }) => theme.colors.dangerSurface};color:${({ theme }) => theme.colors.accentSoft};span{font-size:.65rem;line-height:1.5;}`;
export const AccessGrid = styled.div`display:grid;gap:.1rem;`;
export const AccessItem = styled.div`display:grid;grid-template-columns:auto minmax(0,1fr) auto;align-items:start;gap:${({ theme }) => theme.spacing.sm};padding:${({ theme }) => theme.spacing.md};border-bottom:1px solid ${({ theme }) => theme.colors.line};color:${({ theme }) => theme.colors.primary};strong,span{display:block;}strong{color:${({ theme }) => theme.colors.text};font-size:.72rem;}span{margin-top:.2rem;color:${({ theme }) => theme.colors.textMuted};font-size:.62rem;line-height:1.5;}`;
