import styled from "styled-components";

export const Sidebar = styled.aside`
  display:flex;flex-direction:column;gap:${({theme})=>theme.spacing.md};padding:${({theme})=>theme.spacing.md};
  border-right:1px solid ${({theme})=>theme.colors.line};
  background:radial-gradient(circle at 0 100%,${({theme})=>theme.colors.dangerSurface},transparent 14rem),${({theme})=>theme.colors.surfaceAccent};overflow-y:auto;
  @media(max-width:48rem){border-right:0;border-bottom:1px solid ${({theme})=>theme.colors.line};max-height:16rem;}
`;
export const Header = styled.header`display:flex;align-items:flex-start;justify-content:space-between;gap:${({theme})=>theme.spacing.sm};padding:${({theme})=>`${theme.spacing.xs} 0 ${theme.spacing.sm}`};`;
export const Title = styled.h2`margin:0;font-size:.95rem;`;
export const Privacy = styled.span`display:flex;align-items:center;gap:.3rem;margin-top:.25rem;color:${({theme})=>theme.colors.textSubtle};font-size:.65rem;`;
export const Count = styled.span`min-width:1.8rem;padding:.28rem .45rem;border:1px solid ${({theme})=>theme.colors.line};border-radius:${({theme})=>theme.radius.round};color:${({theme})=>theme.colors.primarySoft};font-size:.65rem;font-weight:700;text-align:center;`;
export const NewButton = styled.button`display:flex;width:100%;align-items:center;justify-content:center;gap:${({theme})=>theme.spacing.xs};border:1px solid ${({theme})=>theme.colors.primary};border-radius:${({theme})=>theme.radius.control};padding:.72rem;background:${({theme})=>theme.colors.primary};color:${({theme})=>theme.colors.background};font:inherit;font-size:.78rem;font-weight:700;cursor:pointer;&:hover:not(:disabled){background:${({theme})=>theme.colors.primarySoft};}&:disabled{cursor:wait;opacity:.6;}`;
export const SectionLabel = styled.span`padding:${({theme})=>`${theme.spacing.xs} 0 .15rem`};color:${({theme})=>theme.colors.textSubtle};font-size:.62rem;font-weight:700;letter-spacing:.11em;text-transform:uppercase;`;
export const List = styled.div`display:grid;gap:.4rem;`;
export const Item = styled.div<{ $active:boolean }>`position:relative;display:grid;grid-template-columns:minmax(0,1fr) auto;align-items:center;gap:.25rem;overflow:hidden;border:1px solid ${({theme,$active})=>$active?theme.colors.lineStrong:theme.colors.line};border-radius:${({theme})=>theme.radius.control};background:${({theme,$active})=>$active?theme.colors.surfaceStrong:"transparent"};&:hover{border-color:${({theme})=>theme.colors.lineStrong};background:${({theme})=>theme.colors.surfaceStrong};}&::before{position:absolute;top:.55rem;bottom:.55rem;left:0;width:.18rem;border-radius:${({theme})=>theme.radius.round};background:${({theme,$active})=>$active?theme.colors.primary:"transparent"};content:"";}`;
export const Open = styled.button<{ $active:boolean }>`overflow:hidden;border:0;border-radius:${({theme})=>theme.radius.control};padding:.65rem .7rem;background:transparent;color:${({theme,$active})=>$active?theme.colors.primarySoft:theme.colors.text};font:inherit;font-size:.82rem;font-weight:${({$active})=>$active?700:500};text-align:left;cursor:pointer;>span{display:block;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;}&:focus-visible{outline:2px solid ${({theme})=>theme.colors.primary};outline-offset:-2px;}`;
export const ItemMeta = styled.small`display:block;overflow:hidden;margin-top:.22rem;color:${({theme})=>theme.colors.textSubtle};font-size:.62rem;font-weight:400;text-overflow:ellipsis;white-space:nowrap;`;
export const Archive = styled.button`display:flex;align-items:center;padding:.5rem;border:0;border-radius:${({theme})=>theme.radius.control};background:transparent;color:${({theme})=>theme.colors.textSubtle};cursor:pointer;&:hover{color:${({theme})=>theme.colors.danger};}&:focus-visible{outline:2px solid ${({theme})=>theme.colors.primary};}`;
export const Empty = styled.div`display:grid;justify-items:center;gap:.35rem;margin:${({theme})=>theme.spacing.lg} 0 0;padding:${({theme})=>theme.spacing.md};border:1px dashed ${({theme})=>theme.colors.lineStrong};border-radius:${({theme})=>theme.radius.control};color:${({theme})=>theme.colors.textSubtle};font-size:.7rem;text-align:center;strong{color:${({theme})=>theme.colors.text};font-size:.76rem;}`;
export const EmptyIcon = styled.span`display:grid;width:2.5rem;height:2.5rem;margin-bottom:.2rem;place-items:center;border-radius:${({theme})=>theme.radius.control};background:${({theme})=>theme.colors.surfaceAccent};color:${({theme})=>theme.colors.primary};`;
