import styled from "styled-components";
import type { CalendarItemKind } from "../../types/calendarTypes";

export const PreviewNote = styled.div`display:flex;align-items:center;gap:${({ theme }) => theme.spacing.sm};padding:.7rem 1rem;border:1px solid ${({ theme }) => theme.colors.line};border-radius:${({ theme }) => theme.radius.control};color:${({ theme }) => theme.colors.textMuted};font-size:.68rem;span{color:${({ theme }) => theme.colors.accentSoft};font-weight:700;}`;
export const Grid = styled.div`display:grid;grid-template-columns:minmax(0,1.8fr) minmax(17rem,.65fr);gap:${({ theme }) => theme.spacing.lg};align-items:start;@media(max-width:68rem){grid-template-columns:1fr;}`;
export const CalendarToolbar = styled.div`display:flex;align-items:center;justify-content:space-between;gap:${({ theme }) => theme.spacing.md};padding:${({ theme }) => theme.spacing.md};border-bottom:1px solid ${({ theme }) => theme.colors.line};>div{display:flex;align-items:center;gap:.4rem;}`;
export const IconButton = styled.button`display:grid;width:2.35rem;height:2.35rem;place-items:center;border:1px solid ${({ theme }) => theme.colors.line};border-radius:${({ theme }) => theme.radius.control};background:transparent;color:${({ theme }) => theme.colors.textMuted};cursor:pointer;&:hover{color:${({ theme }) => theme.colors.primary};}`;
export const MonthLabel = styled.strong`font-size:.85rem;text-transform:capitalize;`;
export const CalendarGrid = styled.div`display:grid;grid-template-columns:repeat(7,minmax(5.2rem,1fr));max-width:100%;overflow-x:auto;`;
export const Weekday = styled.div`padding:.55rem;border-bottom:1px solid ${({ theme }) => theme.colors.line};color:${({ theme }) => theme.colors.textSubtle};font-size:.6rem;font-weight:700;text-align:center;text-transform:uppercase;`;
export const Day = styled.div<{ $outside: boolean }>`min-height:7.25rem;padding:.4rem;border-right:1px solid ${({ theme }) => theme.colors.line};border-bottom:1px solid ${({ theme }) => theme.colors.line};opacity:${({ $outside }) => ($outside ? .34 : 1)};`;
export const DayNumber = styled.span`display:block;margin-bottom:.35rem;color:${({ theme }) => theme.colors.textMuted};font-size:.64rem;font-weight:700;`;
const kindColor = (kind: CalendarItemKind): string => kind === "automation" ? "primary" : kind === "cowork" ? "statusOnline" : "accent";
export const DayEvent = styled.button<{ $kind: CalendarItemKind; $active: boolean }>`display:block;width:100%;overflow:hidden;margin:.22rem 0;border:1px solid ${({ theme, $kind }) => theme.colors[kindColor($kind) as "primary" | "statusOnline" | "accent"]};border-radius:.45rem;padding:.28rem .35rem;background:${({ theme, $active }) => ($active ? theme.colors.surfaceAccent : "transparent")};color:${({ theme }) => theme.colors.text};font:inherit;font-size:.56rem;text-align:left;text-overflow:ellipsis;white-space:nowrap;cursor:pointer;span{margin-right:.25rem;color:${({ theme }) => theme.colors.textSubtle};}`;
export const AgendaList = styled.div`display:grid;`;
export const AgendaItem = styled.button<{ $active: boolean }>`display:grid;grid-template-columns:7rem 4rem minmax(0,1fr);align-items:center;gap:${({ theme }) => theme.spacing.sm};border:0;border-bottom:1px solid ${({ theme }) => theme.colors.line};padding:${({ theme }) => theme.spacing.md};background:${({ theme, $active }) => ($active ? theme.colors.surfaceAccent : "transparent")};color:${({ theme }) => theme.colors.text};font:inherit;text-align:left;cursor:pointer;>strong,>span{font-size:.68rem;color:${({ theme }) => theme.colors.textMuted};}b{display:block;font-size:.74rem;}small{color:${({ theme }) => theme.colors.textSubtle};font-size:.6rem;text-transform:capitalize;}`;
export const Detail = styled.div`display:grid;gap:${({ theme }) => theme.spacing.lg};padding:${({ theme }) => theme.spacing.md};h2{margin:.65rem 0 .3rem;font-size:1.05rem;}p{margin:0;color:${({ theme }) => theme.colors.textMuted};font-size:.7rem;line-height:1.55;}`;
export const DetailGrid = styled.div`display:grid;gap:${({ theme }) => theme.spacing.sm};`;
export const DetailRow = styled.div`display:flex;align-items:center;gap:${({ theme }) => theme.spacing.sm};padding:${({ theme }) => theme.spacing.sm};border-radius:${({ theme }) => theme.radius.control};background:${({ theme }) => theme.colors.background};color:${({ theme }) => theme.colors.primary};span{display:grid;color:${({ theme }) => theme.colors.textSubtle};font-size:.6rem;}strong{color:${({ theme }) => theme.colors.text};font-size:.68rem;}`;
