import styled from "styled-components";

export const Workbench = styled.div`display:grid;grid-template-columns:minmax(18rem,.72fr) minmax(0,1.45fr);gap:${({ theme }) => theme.spacing.lg};align-items:start;@media(max-width:68rem){grid-template-columns:1fr;}`;
export const Library = styled.div`display:grid;gap:${({ theme }) => theme.spacing.md};padding:${({ theme }) => theme.spacing.md};`;
export const LibraryToolbar = styled.div`max-width:100%;overflow:auto;`;
export const SkillList = styled.div`display:grid;gap:${({ theme }) => theme.spacing.sm};`;
export const SkillButton = styled.button<{ $active: boolean }>`display:grid;grid-template-columns:auto minmax(0,1fr);align-items:start;gap:${({ theme }) => theme.spacing.sm};width:100%;border:1px solid ${({ theme, $active }) => ($active ? theme.colors.lineStrong : theme.colors.line)};border-radius:${({ theme }) => theme.radius.control};padding:${({ theme }) => theme.spacing.md};background:${({ theme, $active }) => ($active ? theme.colors.surfaceAccent : theme.colors.background)};color:${({ theme }) => theme.colors.primary};font:inherit;text-align:left;cursor:pointer;&:hover{border-color:${({ theme }) => theme.colors.lineStrong};}`;
export const SkillCopy = styled.div`min-width:0;>strong{display:block;color:${({ theme }) => theme.colors.text};font-size:.78rem;}>span{display:-webkit-box;overflow:hidden;margin-top:.25rem;color:${({ theme }) => theme.colors.textMuted};font-size:.64rem;line-height:1.5;-webkit-box-orient:vertical;-webkit-line-clamp:2;}>div{display:flex;align-items:center;gap:${({ theme }) => theme.spacing.sm};margin-top:.65rem;}small{color:${({ theme }) => theme.colors.textSubtle};font-size:.56rem;text-transform:capitalize;}`;
export const DependencyList = styled.div`display:flex;flex-wrap:wrap;align-items:center;gap:.4rem;padding:${({ theme }) => theme.spacing.md};border-bottom:1px solid ${({ theme }) => theme.colors.line};>span{margin-right:.3rem;color:${({ theme }) => theme.colors.textSubtle};font-size:.6rem;font-weight:700;text-transform:uppercase;}`;
export const Dependency = styled.span`display:inline-flex;align-items:center;gap:.3rem;border:1px solid ${({ theme }) => theme.colors.line};border-radius:${({ theme }) => theme.radius.round};padding:.35rem .55rem;background:${({ theme }) => theme.colors.background};color:${({ theme }) => theme.colors.primarySoft};font-size:.6rem;font-weight:600;`;
