package com.nexoia.audit.model;

/**
 * The security-relevant actions recorded in the unified audit trail.
 *
 * <p>Session events — login, logout, token refresh — are recorded by the access-monitoring module in
 * {@code access_event} instead, because they feed the member's device panel. See D-022.
 */
public enum AuditAction {
    BOOTSTRAP_OWNER_CREATED,
    MEMBER_CREATED,
    MEMBER_DISABLED,
    MEMBER_RESTORED,
    MEMBER_SESSION_REVOKED,
    PROVIDER_CREATED,
    PROVIDER_UPDATED,
    PROVIDER_REMOVED,
    CONVERSATION_CREATED,
    CONVERSATION_RENAMED,
    CONVERSATION_ARCHIVED,
    CONVERSATION_MODEL_SELECTED,
    CONVERSATION_KNOWLEDGE_SELECTED,
    MODEL_REQUEST_STARTED,
    MODEL_REQUEST_COMPLETED,
    MODEL_REQUEST_CANCELLED,
    MODEL_REQUEST_FAILED,
    TOOL_CALL_STARTED,
    TOOL_CALL_COMPLETED,
    TOOL_CALL_DENIED,
    TOOL_CALL_FAILED,
    MCP_CONNECTION_CREATED,
    MCP_CONNECTION_UPDATED,
    MCP_CONNECTION_DISCOVERED,
    MCP_CONNECTION_REMOVED,
    MEMORY_CREATED,
    MEMORY_REMOVED,
    VAULT_CREATED,
    VAULT_ARCHIVED,
    SOURCE_REGISTERED,
    SOURCE_INGESTION_STARTED,
    SOURCE_INGESTION_COMPLETED,
    SOURCE_INGESTION_FAILED,
    SOURCE_ARCHIVED
}
