import styled from "styled-components";

export const Board = styled.div`display:grid;grid-template-columns:minmax(0,1.45fr) minmax(18rem,.65fr);gap:${({ theme }) => theme.spacing.lg};align-items:start;@media(max-width:64rem){grid-template-columns:1fr;}`;
export const Composer = styled.div`display:grid;grid-template-columns:1.2fr .8fr;gap:${({ theme }) => theme.spacing.md};padding:${({ theme }) => theme.spacing.md};button{align-self:end;}@media(max-width:48rem){grid-template-columns:1fr;}`;
export const Objective = styled.div`display:grid;gap:${({ theme }) => theme.spacing.md};padding:${({ theme }) => theme.spacing.md};`;
export const ObjectiveCard = styled.div`padding:${({ theme }) => theme.spacing.lg};border-radius:${({ theme }) => theme.radius.control};background:${({ theme }) => theme.colors.background};>div{display:flex;align-items:center;gap:${({ theme }) => theme.spacing.sm};color:${({ theme }) => theme.colors.primary};span{display:grid;}small{color:${({ theme }) => theme.colors.textSubtle};font-size:.58rem;text-transform:uppercase;}strong{color:${({ theme }) => theme.colors.text};font-size:.88rem;}}>p{margin:.7rem 0 0;color:${({ theme }) => theme.colors.textMuted};font-size:.68rem;line-height:1.55;}`;
export const Progress = styled.div`display:flex;align-items:center;gap:${({ theme }) => theme.spacing.sm};margin-top:${({ theme }) => theme.spacing.md};span{color:${({ theme }) => theme.colors.textSubtle};font-size:.58rem;}div{height:.35rem;flex:1;overflow:hidden;border-radius:${({ theme }) => theme.radius.round};background:${({ theme }) => theme.colors.surfaceAccent};}i{display:block;width:50%;height:100%;background:linear-gradient(90deg,${({ theme }) => theme.colors.primary},${({ theme }) => theme.colors.accent});}`;
export const Plan = styled.div`display:grid;`;
export const Milestone = styled.div<{ $state: "done" | "active" | "waiting" }>`display:grid;grid-template-columns:auto minmax(0,1fr);gap:${({ theme }) => theme.spacing.sm};padding:${({ theme }) => theme.spacing.md};border-left:2px solid ${({ theme, $state }) => ($state === "done" ? theme.colors.statusOnline : $state === "active" ? theme.colors.primary : theme.colors.line)};color:${({ theme, $state }) => ($state === "done" ? theme.colors.statusOnline : $state === "active" ? theme.colors.primary : theme.colors.textSubtle)};strong,span{display:block;}strong{color:${({ theme }) => theme.colors.text};font-size:.72rem;}span{margin-top:.2rem;color:${({ theme }) => theme.colors.textMuted};font-size:.6rem;}`;
export const Activity = styled.div`display:grid;`;
export const ActivityItem = styled.div`display:grid;grid-template-columns:auto minmax(0,1fr);gap:${({ theme }) => theme.spacing.sm};padding:${({ theme }) => theme.spacing.md};border-bottom:1px solid ${({ theme }) => theme.colors.line};color:${({ theme }) => theme.colors.primary};strong,span,small{display:block;}strong{color:${({ theme }) => theme.colors.text};font-size:.7rem;}span{margin-top:.2rem;color:${({ theme }) => theme.colors.textMuted};font-size:.61rem;line-height:1.5;}small{margin-top:.4rem;color:${({ theme }) => theme.colors.textSubtle};font-size:.56rem;}`;
